export enum FlagType {
  Build = "build",
  Claim = "claim",
  Container = "container",
  Decoy = "decoy",
  Defend = "defend",
  Harvest = "harvest",
  HaulerContainer = "hauler_container",
  Heal = "heal",
  Lab = "lab",
  Output = "output",
  Power = "power",
  Reserve = "reserve",
  Range = "range",
  Reaction = "reaction",
  Reverse = "reverse",
  SK = "sk",
  Scout = "scout",
  Stay = "stay",
  Factory = "factory",
  Produce = "produce",
  Transport = "transport"
}
